Repository mjurkowski/WDP-1809-03, pull requests merged in 2018-10, with the labels that each got.

#5 Wdp180903 10 Rozwijane górne menu
  src/index.html
  src/sass/components/_header.scss
Labels: bug

#3 WDP180903-2 - incorrect display counter in shopping cart ('card' component)
  src/index.html
  src/sass/components/_header.scss
Labels: bug

#14 WDP180903-13 Add RWD for 'features' section
  src/index.html
  src/sass/components/_feature-box.scss
Labels: RWD

#16 WDP180903-14 Add RWD for 'products' section
  src/index.html
Labels: RWD

#17 WDP180903-15 - Add RWD for Latest blog
  src/index.html
Labels: RWD

#15 WDP180903-16 - Add footer RWD
  src/index.html
  src/sass/_variables.scss
  src/sass/components/_footer.scss
Labels: RWD

#21 WDP180903-11 RWD - menu główne
  src/index.html
  src/sass/_variables.scss
  src/sass/components/_header.scss
Labels: RWD

#20 WDP180903-12 RWD - topbar i banner
  src/index.html
  src/sass/components/_header.scss
Labels: RWD

#22 WDP180903-26 - Add section 'promoted'
  changelog.md
  src/images/golden-armchair.jpg
  src/images/sitting-room.jpg
  src/index.html
  src/sass/_variables.scss
  src/sass/components/_button.scss
  src/sass/components/_dots.scss
  src/sass/components/_hot-deals.scss
  src/sass/components/_panel-bar.scss
  src/sass/components/_promo-slider.scss
  src/sass/components/_section--features.scss
  src/sass/style.scss
Labels: WIP, enhancement

#25 WDP180903-18 Convert 'products' section's items to slider (alternative)
  changelog.md
  src/index.html
  src/sass/style.scss
  src/sass/vendors/tiny-slider.scss
  src/scripts/app.js
  src/scripts/slider-factory.js
  src/scripts/vendors/bootstrap.min.js
  src/scripts/vendors/bootstrap.min.js.map
  src/scripts/vendors/tiny-slider.js
Labels: JS, RWD, enhancement
